### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by pythoninthegrass** [pythoninthegrass/python_template#11]
While some [GitHub Actions](https://docs.github.com/en/actions) are already present, notably GitLeaks, there's always room for more automation in the CI/CD space.

**Comment by pythoninthegrass** [comment]
For [Hacktoberfest](https://hacktoberfest.com/participation/) participants, PR can be done any time before October. I'll hold off on approval/merging until October 1st so you get credit.

**Comment by laylark** [comment]
I can add a CI action to auto push versioned images to dockerhub, and I can put placeholder docker config in the action.

**Comment by pythoninthegrass** [comment]
Thanks again for the #20 PR! Could definitely use that action on future repos 🥇
